apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-deployment
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: sand1k/mlops-fraud-detection-app:latest
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: AWS_SECRET_ACCESS_KEY
          - name: MLFLOW_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: MLFLOW_S3_ENDPOINT_URL
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: MLFLOW_TRACKING_URI
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: AWS_DEFAULT_REGION

          ports:
            - containerPort: 8000
