name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - fastapi_app/**
  pull_request:
    paths:
      - fastapi_app/**

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TEST_TAG: sand1k/mlops-fraud-transactions-app:test
      LATEST_TAG: sand1k/mlops-fraud-transactions-app:latest


    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: ./fastapi_app
        load: true
        tags: ${{ env.TEST_TAG }}
    
    - name: Run tests
      run: |
        docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e MLFLOW_S3_ENDPOINT_URL -e MLFLOW_TRACKING_URI -e AWS_DEFAULT_REGION ${{ env.TEST_TAG }} conda run --no-capture-output -n mlflow-env pytest -v
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./fastapi_app
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.LATEST_TAG }}
