name: Docker Image CI

on:
  push:
    paths:
      - fastapi_app/**
  pull_request:
    paths:
      - fastapi_app/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./fastapi_app --file fastapi_app/Dockerfile -t fraud_detection_img:$(date +%s)
